# Generated by Django 3.2.10 on 2022-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автор книги', related_name='books', to='catalog.Author', verbose_name='Автор книги'),
        ),
    ]
